package astrotibs.notenoughpets;

import java.io.File;

import astrotibs.notenoughpets.config.GeneralConfig;
import astrotibs.notenoughpets.entity.EntityOcelotNEP;
import astrotibs.notenoughpets.entity.EntityParrotNEP;
import astrotibs.notenoughpets.entity.EntityWolfNEP;
import astrotibs.notenoughpets.events.EventHandlerNEP;
import astrotibs.notenoughpets.proxy.CommonProxy;
import astrotibs.notenoughpets.spawnegg.DispenserBehavior;
import astrotibs.notenoughpets.spawnegg.ItemSpawnEggNEP;
import astrotibs.notenoughpets.spawnegg.SpawnEggRegistry;
import astrotibs.notenoughpets.util.Reference;
import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkRegistry;
import cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper;
import cpw.mods.fml.common.registry.EntityRegistry;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.relauncher.Side;
import net.minecraft.block.BlockDispenser;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.entity.EnumCreatureType;
import net.minecraft.item.Item;
import net.minecraft.util.EnumChatFormatting;
import net.minecraft.world.biome.BiomeGenBase;
import net.minecraftforge.common.MinecraftForge;


@Mod(
		modid = Reference.MOD_ID,
		name = Reference.MOD_NAME,
		version = Reference.VERSION,
		guiFactory = Reference.GUI_FACTORY
		)
public class ModNotEnoughPets
{

	//Copied from Village Names
	public static File configDirectory;
	
	@SidedProxy(clientSide = Reference.CLIENT_PROXY, serverSide = Reference.SERVER_PROXY)
	public static CommonProxy PROXY;

	public static SimpleNetworkWrapper NECNetworkWrapper;
	
	public static ItemSpawnEggNEP spawnEgg;
	public static CreativeTabs spawnEggTabNEC = new CreativeTabs(Reference.MOD_ID)
	{
		@Override
		public Item getTabIconItem() {return spawnEgg;}
	};
	
	
    @EventHandler
    public void preInit(FMLPreInitializationEvent event)
    {
    	
		// Copied from ChocoCraft Plus
		configDirectory = new File(event.getModConfigurationDirectory(), "notenoughpets.cfg");//new File(ModChocoCraft.configFolder, "chococraft.json");
		GeneralConfig.init(configDirectory);//new File(configDirectory, "general.cfg"));
		
		// Spawn egg stuff
		spawnEgg = new ItemSpawnEggNEP();
		GameRegistry.registerItem(spawnEgg, spawnEgg.getUnlocalizedName());
		BlockDispenser.dispenseBehaviorRegistry.putObject(spawnEgg, new DispenserBehavior());
		
    	// Cat listener:
    	MinecraftForge.EVENT_BUS.register(new EventHandlerNEP());
    	FMLCommonHandler.instance().bus().register(new EventHandlerNEP()); // world events have to be registered on FMLCommonHandler
    	

		// The following overrides the mcmod.info file!
		// Adapted from Jabelar's Magic Beans:
		// https://github.com/jabelar/MagicBeans-1.7.10/blob/e48456397f9c6c27efce18e6b9ad34407e6bc7c7/src/main/java/com/blogspot/jabelarminecraft/magicbeans/MagicBeans.java
        event.getModMetadata().autogenerated = false ; // stops it from complaining about missing mcmod.info
        
        event.getModMetadata().name = 			// name 
        		EnumChatFormatting.YELLOW + 
        		Reference.MOD_NAME;
        
        event.getModMetadata().version = 		// version 
        		Reference.VERSION;
        
        event.getModMetadata().credits = 		// credits 
        		EnumChatFormatting.AQUA +
        		"Vanilla textures by Jappa. Custom by AstroTibs and by submission.";
        
        event.getModMetadata().authorList.clear();
        event.getModMetadata().authorList.add(  // authorList - added as a list
        		EnumChatFormatting.BLUE +
        		"AstroTibs");
        
        
        event.getModMetadata().description = 	// description
	       		EnumChatFormatting.YELLOW +
	       		"Adds new cat/dog/parrot skins and behavior settings. Cats and dogs spawn as strays in villages.";
        
        event.getModMetadata().logoFile = "assets"+File.separator+"notenoughpets"+File.separator+"nep_banner.png";

    }
    
    @EventHandler
    public void init(FMLInitializationEvent event)
    {
    	// The new general Forge entity registry:
    	
    	int entityIDs = 0; // Increment this to make sure everything has its own model register
    	
    	// Changed names to reference constants
    	EntityRegistry.registerModEntity(EntityOcelotNEP.class, Reference.MOB_OCELOT_NEP, entityIDs++, this, 64, 3, true);
    	EntityRegistry.registerModEntity(EntityWolfNEP.class, Reference.MOB_WOLF_NEP, entityIDs++, this, 64, 3, true);
	    EntityRegistry.registerModEntity(EntityParrotNEP.class, Reference.MOB_PARROT_NEP, entityIDs++, this, 64, 3, true);
    
    	
    	PROXY.registerRender();
    	PROXY.init(event);
    	
    }
    
    // Add spawn eggs to the registry
	@EventHandler 
	public void postInit(FMLPostInitializationEvent event)
	{
		SpawnEggRegistry.addAllSpawnEggs();
	}
    
    private static int getRGBInt(int rInt, int gInt, int bInt)
	{
		return (rInt << 16) + (gInt << 8) + bInt;
	}
    
}
